<?php

function bouquet_theme($existing, $type, $theme, $path) {
  return [
    'bouquet_email' => array(
      'variables' => array('mail_data' => []),
    ),
  ];
}

/** * Implements hook_mail(). */
function bouquet_mail($key, &$message, $params) {

  switch ($key) { 

	  case 'optalgarden_mail':
      $message['headers']['MIME-Version'] = '1.0';
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['headers']['Content-Transfer-Encoding'] = '8Bit';  
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = "Added new bouquet Successfully";

      $message_list = $params['message'];
      $message_list['subject'] = 'Mail triggered Successfully';

      $body_data = [
        '#theme' => 'bouquet_email',
        '#mail_data' => $message_list,
      ];
      $message['body'][] = \Drupal::service('renderer')->renderPlain($body_data);
      break;  
   }
}